import CompletedTesting from "./components/CompletedTesting";
import TestingDatasetInfo from "./components/TestingDatasetInfo";
import TestingModelInfo from "./components/TestingModelInfo";

export default function TestingDisplayPage({ params }) {
  // TODO: fetch testing info by id
  const testingId = params.id;

  // TODO: 是否事客观测试
  const isAutomatedTest = true;

  return (
    <div className="flex w-full flex-col space-y-5">
      <h1 className=" font-mono text-4xl font-bold text-primary">
        mmlu_select 客观测试
      </h1>
      <div>
        <progress
          className="progress h-3 w-full"
          value="70"
          max="100"
        ></progress>
        <p className="text-gray-500">
          正在测试第x条问题: "The cyclic subgroup of Z_24 generated by 18 has
          ......
        </p>
        <p className="text-gray-500">2023/12/4 00:00:00开始 • 已用时 x 分钟</p>
      </div>
      <h2 className="text-2xl font-bold">数据集</h2>
      <TestingDatasetInfo />
      <h2 className="text-2xl font-bold">模型</h2>
      <TestingModelInfo />
      <TestingModelInfo />
      <h2 className="text-2xl font-bold">已完成测试的模型</h2>
      <CompletedTesting />
      <CompletedTesting />
    </div>
  );
}
