import Link from "next/link";

import ResultTable from "./components/CompletedTesting";
import TestingDatasetInfo from "./components/TestingDatasetInfo";
import TestingModelInfo from "./components/TestingModelInfo";
import { EyeIcon, ScaleIcon } from "@heroicons/react/24/solid";

export default function TestingDisplayPage({ params }) {
  // TODO: fetch testing info by id
  const testingId = params.id;

  // TODO: Some examples, 0-客观测试 1-主观测试, 2- 对抗测试
  const type = testingId;

  let testingName = "";
  if (type == 0) {
    testingName = "mmlu_select 客观测试";
  } else if (type == 1) {
    testingName = "zbench_common 主观测试";
  } else {
    testingName = "zbench_common 对抗测试";
  }
  // const currentProgress =
  //   type == 0
  //     ? '正在测试第x/xx条问题: "The cyclic subgroup of Z_24 generated by 18 has ......, 已用时xx秒'
  //     : "已经主观测试了x/xx题,";
  let currentProgress = "";
  if (type == 0) {
    currentProgress =
      '正在测试第x/xx条问题: "The cyclic subgroup of Z_24 generated by 18 has ......, 已用时xx秒';
  } else if (type == 1) {
    currentProgress = "已经主观测试了x/xx题,";
  } else if (type == 2) {
    currentProgress = "已经对抗测试了x/xx题,";
  }

  const startTime = "2023/12/4 00:00:00";

  return (
    <div className="flex w-full flex-col space-y-5">
      <h1 className=" font-mono text-4xl font-bold text-primary">
        {testingName}
      </h1>
      <div>
        <progress
          className="progress h-3 w-full"
          value="70"
          max="100"
        ></progress>
        <p className="text-gray-500">{currentProgress}</p>
        <p className="text-gray-500">{startTime}开始</p>
      </div>

      {type == 1 && (
        <Link
          href={`${testingId}/human-evaluation`}
          className="btn btn-accent w-max rounded-3xl"
        >
          <EyeIcon className="mr-2 h-5 w-5" />
          继续主观测试
        </Link>
      )}

      {type == 2 && (
        <Link
          href={`${testingId}/comparative-evaluation`}
          className="btn btn-accent w-max rounded-3xl"
        >
          <ScaleIcon className="mr-2 h-5 w-5" />
          继续对抗测试
        </Link>
      )}

      <h2 className="text-2xl font-bold">数据集</h2>
      <TestingDatasetInfo />
      <h2 className="text-2xl font-bold">模型</h2>
      {/* TODO: examples */}
      <TestingModelInfo />
      <TestingModelInfo />
      <h2 className="text-2xl font-bold">已完成测试的模型</h2>
      {/* TODO: examples */}
      <ResultTable type={type} />
      <ResultTable type={type} />
    </div>
  );
}
