import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { ClerkProvider } from '@clerk/nextjs'
import { zhCN } from "@clerk/localizations";


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={zhCN}>
      <html lang="zh">
        <body className='min-h-screen flex flex-col justify-between'>
          <Navbar />
          <main className="flex-1 flex-col items-center justify-between px-24 py-6">
            {children}
          </main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
