"use client";
import { DataGrid } from "@mui/x-data-grid";

// TODO
const columns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "isCorrect", headerName: "是否正确", width: 100 },
  { field: "type", headerName: "类型", width: 150 },
  { field: "question", headerName: "问题", width: 300 },
  { field: "generatedAnswer", headerName: "生成答案", width: 120 },
  { field: "correctAnswer", headerName: "正确答案", width: 120 },
  { field: "optionA", headerName: "选项 A", width: 100 },
  { field: "optionB", headerName: "选项 B", width: 100 },
  { field: "optionC", headerName: "选项 C", width: 100 },
  { field: "optionD", headerName: "选项 D", width: 100 },
];

const rows = [
  {
    id: 1,
    isCorrect: "❌",
    type: "abstract_algebra",
    question: "The cyclic subgroup of Z_24 generated by 18 has order",
    generatedAnswer: "B",
    correctAnswer: "A",
    optionA: "4",
    optionB: "8",
    optionC: "12",
    optionD: "6",
  },
  {
    id: 2,
    isCorrect: "✅",
    type: "abstract_algebra",
    question:
      "Statement 1 | A permutation that is a product of m even permutations and n odd permutations is an even permutation if and only if n is even. Statement 2 | Every group is isomorphic to a group of permutations.",
    generatedAnswer: "A",
    correctAnswer: "A",
    optionA: "True, True",
    optionB: "False, False",
    optionC: "True, False",
    optionD: "False, True",
  },
  {
    id: 3,
    isCorrect: "✅",
    type: "college_computer_science",
    question:
      "Sometimes the object module produced by a compiler includes information (from the symbol table) mapping all source program names to their addresses. The most likely purpose of this information is",
    generatedAnswer: "A",
    correctAnswer: "A",
    optionA: "for use as input to a debugging aid",
    optionB: "to increase the run-time efficiency of the program",
    optionC:
      "for the reduction of the symbol-table space needed by the compiler",
    optionD: "to tell the loader where each variable belongs",
  },
  // Add more rows as per your data
];

export default function CompletedTesting() {
  return (
    // // tabIndex={0} attribute is necessary to make the div focusable
    // <div tabIndex={0} className="collapse collapse-arrow border bg-white p-2 ">
    // <div className="items-center collapse-title flex space-x-3">
    //   <div className="font-mono text-xl font-bold">GPT-4</div>
    //   <div className="font-medium text-gray-400">正确率66% • 用时xx分钟</div>
    // </div>
    //   <div className="collapse-content overflow-x-auto">
    //     <div className="overflow-x-auto">
    //   <DataGrid
    //   rows={rows}
    //   columns={columns}
    //   initialState={{
    //     pagination: {
    //       paginationModel: { page: 0, pageSize: 5 },
    //     },
    //   }}
    //   pageSizeOptions={[5, 10]}
    //   checkboxSelection
    // />
    //       {/* <table className="table table-xs">
    //         <thead>
    //           <tr>
    //             <th></th>
    //             <th>是否正确</th>
    //             <th>类型</th>
    //             <th>问题</th>
    //             <th>生成答案</th>
    //             <th>正确答案</th>
    //             <th>选项 A</th>
    //             <th>选项 B</th>
    //             <th>选项 C</th>
    //             <th>选项 D</th>
    //           </tr>
    //         </thead>
    //         <tbody>
    //           <tr>
    //             <th>1</th>
    //             <td>❌</td>
    //             <td>abstract_algebra</td>
    //             <td>The cyclic subgroup of Z_24 generated by 18 has order</td>
    //             <td>B</td>
    //             <td>A</td>
    //             <td>4</td>
    //             <td>8</td>
    //             <td>12</td>
    //             <td>6</td>
    //           </tr>
    //           <tr>
    //             <th>2</th>
    //             <td>✅</td>
    //             <td>abstract_algebra</td>
    //             <td>
    //               Statement 1 | A permutation that is a product of m even
    //               permutations and n odd permutations is an even permutation if
    //               and only if n is even. Statement 2 | Every group is isomorphic
    //               to a group of permutations.
    //             </td>
    //             <td>A</td>
    //             <td>A</td>
    //             <td>True, True</td>
    //             <td>False, False</td>
    //             <td>True, False</td>
    //             <td>False, True</td>
    //           </tr>
    //           <tr>
    //             <th>3</th>
    //             <td>✅</td>
    //             <td>college_computer_science</td>
    //             <td>
    //               Sometimes the object module produced by a compiler includes
    //               information (from the symbol table) mapping all source program
    //               names to their addresses. The most likely purpose of this
    //               information is
    //             </td>
    //             <td>A</td>
    //             <td>A</td>
    //             <td>for use as input to a debugging aid</td>
    //             <td>to increase the run-time efficiency of the program</td>
    //             <td>
    //               for the reduction of the symbol-table space needed by the
    //               compiler
    //             </td>
    //             <td>to tell the loader where each variable belongs</td>
    //           </tr>
    //         </tbody>
    //       </table> */}
    //     </div>
    //   </div>
    // </div>

    <div className="collapse collapse-arrow border bg-white">
      <input type="checkbox" />
      <div className="collapse-title flex items-center space-x-3">
        <div className="font-mono text-xl font-bold">GPT-4</div>
        <div className="font-medium text-gray-400">正确率66% • 用时xx分钟</div>
      </div>
      <div className="collapse-content overflow-x-auto">
        <DataGrid
          rows={rows}
          columns={columns}
          initialState={{
            pagination: {
              paginationModel: { page: 0, pageSize: 5 },
            },
          }}
          pageSizeOptions={[5, 10]}
        />
      </div>
    </div>
  );
}
