"use client";
import { DataGrid } from "@mui/x-data-grid";

// TODO
const columns = [
  { field: "id", headerName: "ID", width: 70 },
  { field: "isCorrect", headerName: "是否正确", width: 100 },
  { field: "type", headerName: "类型", width: 150 },
  { field: "question", headerName: "问题", width: 300 },
  { field: "generatedAnswer", headerName: "生成答案", width: 120 },
  { field: "correctAnswer", headerName: "正确答案", width: 120 },
  { field: "optionA", headerName: "选项 A", width: 100 },
  { field: "optionB", headerName: "选项 B", width: 100 },
  { field: "optionC", headerName: "选项 C", width: 100 },
  { field: "optionD", headerName: "选项 D", width: 100 },
];

const rows = [
  {
    id: 1,
    isCorrect: "❌",
    type: "abstract_algebra",
    question: "The cyclic subgroup of Z_24 generated by 18 has order",
    generatedAnswer: "B",
    correctAnswer: "A",
    optionA: "4",
    optionB: "8",
    optionC: "12",
    optionD: "6",
  },
  {
    id: 2,
    isCorrect: "✅",
    type: "abstract_algebra",
    question:
      "Statement 1 | A permutation that is a product of m even permutations and n odd permutations is an even permutation if and only if n is even. Statement 2 | Every group is isomorphic to a group of permutations.",
    generatedAnswer: "A",
    correctAnswer: "A",
    optionA: "True, True",
    optionB: "False, False",
    optionC: "True, False",
    optionD: "False, True",
  },
  {
    id: 3,
    isCorrect: "✅",
    type: "college_computer_science",
    question:
      "Sometimes the object module produced by a compiler includes information (from the symbol table) mapping all source program names to their addresses. The most likely purpose of this information is",
    generatedAnswer: "A",
    correctAnswer: "A",
    optionA: "for use as input to a debugging aid",
    optionB: "to increase the run-time efficiency of the program",
    optionC:
      "for the reduction of the symbol-table space needed by the compiler",
    optionD: "to tell the loader where each variable belongs",
  },
  // Add more rows as per your data
];

export default function CompletedTesting() {
  return (
    <div className="collapse collapse-arrow border bg-white">
      <input type="checkbox" />
      <div className="collapse-title flex items-center space-x-3">
        <div className="font-mono text-xl font-bold">GPT-4</div>
        <div className="font-medium text-gray-400">正确率66% • 用时xx分钟</div>
      </div>
      <div className="collapse-content overflow-x-auto">
        <DataGrid
          rows={rows}
          columns={columns}
          initialState={{
            pagination: {
              paginationModel: { page: 0, pageSize: 5 },
            },
          }}
          pageSizeOptions={[5, 10]}
        />
      </div>
    </div>
  );
}
